# Generated by Django 5.0.1 on 2024-01-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('table', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('resturent_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.resturentowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResturentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.customer')),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturent')),
                ('purchased_items', models.ManyToManyField(to='restaurant.resturentmenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResturentTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerTableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.customer')),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturent')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturenttables')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
