# Generated by Django 5.0.1 on 2024-01-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchase',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='customerpurchase',
            name='purchased_items',
        ),
        migrations.RemoveField(
            model_name='customertablebooking',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='resturent',
            name='table',
        ),
        migrations.RenameModel(
            old_name='ResturentMenu',
            new_name='ResturentFoodItem',
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('customer_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customerpurchase')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.resturentfooditem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
