# Generated by Django 5.0.1 on 2024-01-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_customerpurchase_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='resturent_image',
            field=models.ImageField(blank=True, null=True, upload_to='resturent_images/'),
        ),
    ]
