# Generated by Django 5.0.1 on 2024-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_resturent_resturent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertablebooking',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customertablebooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customertablebooking',
            name='no_of_diners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customertablebooking',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customertablebooking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customertablebooking',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
