# Generated by Django 5.0.1 on 2024-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_customerorderitem_customerorderitemdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertablebooking',
            name='table_numbers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
