# Generated by Django 5.0.1 on 2024-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_customertablebooking_table_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resturent',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
