# Generated by Django 5.0.1 on 2024-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_resturent_destination_resturent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
