# Generated by Django 5.0.1 on 2024-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_customerorderitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitemdetails',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
